module.exports = {
  10: [
    // KRAĆE / STANDARD
    "Top Service.",
    "Sehr zufrieden mit der Lieferung.",
    "Alles perfekt gelaufen.",
    "Pünktlich und freundlich.",
    "Sehr professionell.",
    "Absolut empfehlenswert.",
    "Keine Probleme, alles bestens.",
    "Der Fahrer war sehr nett.",
    "Schnelle und saubere Zustellung.",
    "Perfekter Ablauf.",
    "Alles wie erwartet.",
    "Zustellung ohne Verzögerung.",
    "Sehr guter Service.",
    "Paket unbeschädigt angekommen.",
    "Freundliche Übergabe.",
    "Besser geht es nicht.",
    "Einwandfreie Lieferung.",
    "Top Leistung.",
    "Sehr zuverlässig.",
    "Gerne wieder.",
    "Alles super.",
    "Sehr angenehme Zustellung.",
    "Professioneller Fahrer.",
    "Reibungsloser Ablauf.",
    "Zustellung war optimal.",
    "Keine Beanstandungen.",
    "Alles top.",
    "Sehr gut organisiert.",
    "Paket sicher übergeben.",
    "Volle Zufriedenheit.",

    // 🆕 STORY / LJUDSKE PORUKE
    "Der Fahrer hat sich extra Zeit genommen und mir geholfen, obwohl es schon spät war. Sehr engagiert und freundlich.",
    "Man merkt sofort, dass hier Profis arbeiten. Der Fahrer wusste genau, was zu tun ist, und war sehr hilfsbereit.",
    "Der Zusteller hat kurz angerufen und eine Lösung gefunden, damit ich das Paket sicher bekomme. Top Einsatz.",
    "Sehr gute Organisation, der Fahrer war ruhig, höflich und absolut professionell. So wünscht man sich das.",
    "Ich kenne die Firma schon lange, aber seit der Zusammenarbeit mit GLS ist der Service deutlich besser geworden.",
    "Der Fahrer ist sogar ein paar Schritte extra gegangen, um mir zu helfen. Wirklich vorbildlich.",
    "Man merkt, dass hier nicht nur geliefert wird, sondern dass Service ernst genommen wird.",
    "Sehr gut geführter Betrieb, der Fahrer war bestens informiert und freundlich.",
    "Der Zusteller hat alles sauber erklärt und darauf geachtet, dass das Paket sicher ankommt.",
    "Großes Lob an Fahrer und Organisation – alles lief ruhig, strukturiert und professionell."
  ],

  9: [
    // KRAĆE / STANDARD
    "Sehr gute Lieferung.",
    "Zufrieden mit dem Service.",
    "Alles gut gelaufen.",
    "Freundlicher Fahrer.",
    "Pünktlich geliefert.",
    "Keine Probleme.",
    "Guter Service.",
    "Zustellung in Ordnung.",
    "Alles ok.",
    "Saubere Übergabe.",
    "Angenehme Zustellung.",
    "Gute Erfahrung.",
    "Paket heil angekommen.",
    "Service passt.",
    "Alles wie geplant.",
    "Zuverlässig.",
    "Freundlich und korrekt.",
    "Gerne wieder.",
    "Guter Ablauf.",
    "Zusteller war nett.",
    "Keine Beschwerden.",
    "Ordentliche Zustellung.",
    "Alles gut.",
    "Positiver Eindruck.",
    "Guter Standard.",
    "Solide Leistung.",
    "Zufrieden.",
    "Hat gepasst.",
    "Alles okay.",
    "Gute Arbeit.",

    // 🆕 STORY
    "Der Fahrer war sehr freundlich und hat kurz gewartet, obwohl ich nicht sofort da war.",
    "Alles lief gut organisiert, der Zusteller wusste genau Bescheid.",
    "Man merkt eine gute Abstimmung zwischen Fahrer und Firma.",
    "Der Fahrer hat mitgedacht und mir die Zustellung erleichtert.",
    "Seit GLS-Partner ist die Zustellung spürbar zuverlässiger.",
    "Angenehmer Kontakt, keine Hektik, alles ruhig erklärt.",
    "Der Zusteller war hilfsbereit und lösungsorientiert.",
    "Gute Organisation, alles lief ohne Stress.",
    "Der Fahrer hat einen guten Eindruck hinterlassen.",
    "Service insgesamt sehr ordentlich."
  ],

  8: [
    // KRAĆE / STANDARD
    "Lieferung war in Ordnung.",
    "Alles ok.",
    "Keine größeren Probleme.",
    "Zustellung akzeptabel.",
    "Paket angekommen.",
    "Service war ok.",
    "Wie erwartet.",
    "Ganz in Ordnung.",
    "Durchschnittlich gut.",
    "Passt.",
    "Ordentliche Lieferung.",
    "Zusteller korrekt.",
    "Kein Grund zur Beschwerde.",
    "Alles normal.",
    "Zufriedenstellend.",
    "Standard Zustellung.",
    "Okay gelaufen.",
    "Service akzeptabel.",
    "Im Großen und Ganzen gut.",
    "Paket heil.",
    "Zustellung ok.",
    "Kein Problem.",
    "Alles ausreichend.",
    "Neutral.",
    "War okay.",
    "Durchschnitt.",
    "In Ordnung.",
    "Passt schon.",
    "Nichts Besonderes.",
    "Akzeptabel.",

    // 🆕 STORY
    "Der Fahrer war korrekt und hat seinen Job ordentlich gemacht.",
    "Zustellung ohne Probleme, alles im normalen Rahmen.",
    "Der Fahrer war sachlich, aber hilfsbereit.",
    "Organisation wirkt solide und eingespielt.",
    "Kein besonderer Aufwand, aber zuverlässig erledigt.",
    "Der Zusteller war ruhig und professionell.",
    "Alles lief wie geplant.",
    "Service insgesamt okay.",
    "Der Fahrer hat korrekt gehandelt.",
    "Ordentliche Arbeit ohne Zwischenfälle."
  ],

  7: [
    "Zustellung war ok.",
    "Service durchschnittlich.",
    "Könnte besser sein.",
    "Nicht optimal.",
    "War in Ordnung.",
    "Leichte Verzögerung.",
    "Standard.",
    "Ganz okay.",
    "Akzeptabel.",
    "Mittelmäßig.",
    "Service ok.",
    "Nichts Besonderes.",
    "Erledigt.",
    "Normal.",
    "Ausreichend.",
    "Keine Erwartungen.",
    "Funktioniert.",
    "Okay.",
    "Nicht schlecht.",
    "Zustellung erhalten.",
    "Kein Drama.",
    "War ok.",
    "Durchschnittlich.",
    "Passt.",
    "Neutral.",
    "Erfüllt Zweck.",
    "Akzeptabler Service.",
    "Nicht bemerkenswert.",
    "Standard Lieferung.",
    "Okay soweit."
  ]
};
